### ISSUE TITLE
javascript上传 java生成签名

### ISSUE THREAD

**Issue by caokaizz** [tencentyun/cos-java-sdk-v5#10]
javascript上传 java生成签名的demo好像没有 只有php和node.js的吗?

**Comment by liuyongqing** [comment]
预签名url相关可以参考sdk官网文档，和这个demo：https://github.com/tencentyun/cos-java-sdk-v5/blob/master/src/main/java/com/qcloud/cos/demo/GeneratePresignedUrlDemo.java
