### ISSUE TITLE
Provides transitive vulnerable dependency org.bouncycastle:bcprov-jdk15on:1.67 Vulnerability with high severity found 

### ISSUE THREAD

**Issue by leshalv** [tencentyun/cos-java-sdk-v5#103]
https://advisory.checkmarx.net/advisory/vulnerability/Cxa9261daf-3755/

**Comment by leshalv** [comment]
怎么给关闭了呀 @Jeffreykzli

**Comment by leshalv** [comment]
bcprov-jdk15on:1.67 这个依赖有漏洞，需要处理一下的

**Comment by leshalv** [comment]
<img width="506" alt="image" src="https://github.com/tencentyun/cos-java-sdk-v5/assets/30397655/3a1c0c6c-32dc-4ce1-b4f8-8536eac37bd2">

**Comment by Jeffreykzli** [comment]
我们会排期安排升级依赖哈
