### ISSUE TITLE
endPointSuffix 问题

### ISSUE THREAD

**Issue by lyu00001** [tencentyun/cos-java-sdk-v5#12]
您好，我想问下在5.4.4最新的版本能用EndPoint吗？
我在ClientConfig 这个类里找到里，但是endPointSuffix 是null。所以我想了解下具体的用法？？
@wucheng

**Comment by wucheng** [comment]
目前是设置endpintsuffix，sdk会默认在endpoint前面加上bucket-appid, 这里主要用于后续动态加速或者混合云等场景需要自定义域名的场景，因此未在文档或者demo中体现
如果使用cos建议直接通过设置region的方法

**Comment by lyu00001** [comment]
endpintsuffix 的设置跟zone会不会有冲突？？

**Comment by lyu00001** [comment]
或者说两者有重叠的地方？

**Comment by lyu00001** [comment]
比如说我在new ClientConfig 里面开始初始化设置了region。 然后我又设置了endpointsuffix。两个假如不同是否，是否就有冲突？？或者优先用那个？？
@wucheng

**Comment by wucheng** [comment]
endpointsuffix的优先级高于region，如果设置了endpointsuffix，region就不起作用了
