### ISSUE TITLE
5.6.36 tag缺失问题

### ISSUE THREAD

**Issue by CChengjie** [tencentyun/cos-java-sdk-v5#122]
我们发现了5.6.36版本在maven中发布了，但是github中并没有相应的tag;

请问tag缺失的原因是什么？（发现提交记录里有相关版本发布的readme）

- a、该版本存在代码问题，如存在漏洞、兼容性问题、界面方面问题等。
- b、该版本出现功能性问题，如功能规划不合理、基础功能不能使用等。
- c、忘记打tag
- d、不在意或者嫌操作麻烦
- e、其他原因，_

2） 针对该问题，我们提出了一个方法，能够找到version 可能对应的真实commit， 以帮助开发者快速定位问题代码，完成漏洞修复。 以下是我们方法给出的可能的真实commits，请您帮忙确认下是否包含了真实的commit，如果不是，应该是哪一个？

['a01c54fcd40da235eac305a6e8d2fd3d08859d9b', 'a5d349483b95859f1b0ba7777aba4bcf424cfb5c', '97249264e5a36811ce4cd74ef22c3badc6a6b37f', '6ff5f913c7ee4a95c2083b0abcf7625cc2847733']

**Comment by Jeffreykzli** [comment]
19fa18ae7ed3c8cfb0cf3f869160deea823b51c5
