### ISSUE TITLE
设置EndPointSuffix后，listBuckets 接口报错

### ISSUE THREAD

**Issue by wangzw** [tencentyun/cos-java-sdk-v5#13]
EndPointSuffix 设置为 cos.ap-beijing.myqcloud.com， listBuckets 接口报错

报错信息
```
com.qcloud.cos.exception.CosServiceException: Missing required header for this request: Appid (Status Code: 400; Error Code: InvalidRequest; Request ID: NWI3YzJlYjdfOGMyODVkNjRfYWZjMl9mZWZiN2E=); Trace ID: OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODczNTBmNjMwZmQ0MTZkMjg0NjlkNTYyNmY4ZTRkZTk0NzgyODEyZmZkMzFkOTczNGZhZTI1N2FiZmI0M2FiNzBmYTQ5MzFmODcxMjlkN2RjMGI3ZjU1NWQ2NjkxMDE3N2M=
```

出错原因： 请求地址错误
```
service.cos.ap-beijing.myqcloud.com
```

**Comment by wangzw** [comment]
@wucheng

**Comment by wucheng** [comment]
抱歉，这里没有在文档里明确体现，给你这边造成困扰
ListBucket的域名比较特殊，EndpointSuffix是.cos.myqcloud.com（5.4.4及之前），service.cos.myqcloud.com(5.4.5之后，目前正在发布中)
建议如果不是有特定的自定义域名或者使用混合云私有云的需求
使用公有云COS，请使用region的方式

**Comment by wangzw** [comment]
把 EndpointSuffix 设置成 .cos.myqcloud.com（5.4.4及之前），service.cos.myqcloud.com(5.4.5之后)，其它的接口又不能工作了吧？

从代码里看，listBucket 和其它 API 对 EndpointSuffix 的设置是冲突的。

我提交了一个 pull request #14 修复这个冲突。

@wucheng

**Comment by wucheng** [comment]
嗯 刚看了你的pull request，多谢宝贵意见
但是不能简单合入，因为COS的SDK还应用于云这边一些其他场景，比如混合云和专有云等，他们的域名比较特殊。
endpintsuffix最早就是为了兼容引入
所以目前的SDK，如果要使用endpointsuffix必须要使用service.cos.myqcloud.com这个endpointsuffix。

**Comment by wangzw** [comment]
也就是说，在私有云环境下，设置 endpointsuffix 后，listbucket 和其它 API 不能同时使用？

**Comment by liuyongqing** [comment]
私有云环境下，可以实现EndpointBuilder接口，分别构造普通API的endpoint和listBucket的endpoint，并设置到ClientConfig中。
