### ISSUE TITLE
Key 包含空格导致GenerateDocPreviewUrl 出现SignatureDoesNotMatch

### ISSUE THREAD

**Issue by aishang1993** [tencentyun/cos-java-sdk-v5#162]
SDK语言: Java SDK
SDK版本号: 5.6.167
Key 包含空格导致GenerateDocPreviewUrl 出现SignatureDoesNotMatch

![image](https://github.com/tencentyun/cos-java-sdk-v5/assets/20903014/b2abe905-9c29-44f6-87f4-c83035ecbc42)

![image](https://github.com/tencentyun/cos-java-sdk-v5/assets/20903014/09c4bfd8-2cbf-4e01-902c-12a57f224a08)

DocHtmlRequest 中的key 如果包含空格这句代码会报错：URIBuilder uriBuilder = new URIBuilder(urlStr)。
将空格替换为 “%20”，又会导致SignatureDoesNotMatch：因为 buildAuthorizationStr 函数接收的key的空格被替换为“%20”了。

**Comment by 563750789** [comment]
问题修复中 预计下个版本带出
