### ISSUE TITLE
上传完成后，返回结果没有完整的文件访问路径

### ISSUE THREAD

**Issue by tianmuwu** [tencentyun/cos-java-sdk-v5#17]
希望上传完成后，返回值当中加入完整的访问路径

**Comment by liuyongqing** [comment]
您上传的时候，是自己指定的存储桶和访问路径，后续访问该存储桶中的该对象，可以生成预签名url，可参考官网文档或demo:https://github.com/tencentyun/cos-java-sdk-v5/blob/master/src/main/java/com/qcloud/cos/demo/GeneratePresignedUrlDemo.java
