### ISSUE TITLE
cos-java-sdk作为一个api，希望不要直接引入slf4j-log4j12，改成引入slf4j-api

### ISSUE THREAD

**Issue by vmwell** [tencentyun/cos-java-sdk-v5#18]
cos-java-sdk作为一个api，希望不要直接引入slf4j-log4j12，改成引入slf4j-api

**Comment by wjj0508403034** [comment]
顶楼上，我们项目里用了logback，然后在引用你的包，结果就是没办法打log了，去也去不掉

**Comment by liuyongqing** [comment]
谢谢大家的建议，我们这边也有规划替换为slf4j的api

**Comment by liuyongqing** [comment]
@vmwell, @wjj0508403034 ，两位同学，cos java sdk v5.5.8这里已经引入slf4j-api。
