### ISSUE TITLE
acl设置了无效 没有删除文件夹功能

### ISSUE THREAD

**Issue by boolBit** [tencentyun/cos-java-sdk-v5#2]
为什么 cosclient.setObjectAcl(ClientConfig.BUCKET_NAME,  "123.m4a", CannedAccessControlList.Private)
设置为私有读写，浏览器还是能访问.... 这个有什么作用？
没有删除文件夹功能，貌似list某个文件夹下的文件和目录的功能都没

**Comment by liuyongqing** [comment]
设置了对象的私有读写，还能访问，可能由于您这边的浏览器缓存。列出某个前缀下的目录，您可以参考GETBucket API和如下的cos java sdk例子：https://github.com/tencentyun/cos-java-sdk-v5/blob/master/src/main/java/com/qcloud/cos/demo/ListObjectsDemo.java
