### ISSUE TITLE
依赖的BC库版本太低，漏洞多

### ISSUE THREAD

**Issue by sagaxu** [tencentyun/cos-java-sdk-v5#205]
![Screenshot 2024-07-03 at 14-43-25 Maven Repository com qcloud » cos_api » 5 6 219 1](https://github.com/tencentyun/cos-java-sdk-v5/assets/347750/51f4045e-f31f-4265-bfa9-4a7be128be4b)

[https://mvnrepository.com/artifact/com.qcloud/cos_api/5.6.219.1](https://mvnrepository.com/artifact/com.qcloud/cos_api/5.6.219.1)

**Comment by Dzkol** [comment]
此问题已经录了需求单，待排期修复
