### ISSUE TITLE
ObjectMetadata.addUserMetadata 当 value 为中文时，请求乱码，导致签名错误

### ISSUE THREAD

**Issue by sqzr** [tencentyun/cos-java-sdk-v5#57]
version:5.6.17

![image](https://user-images.githubusercontent.com/5857946/76810151-0e881000-6828-11ea-9310-842eb0773dad.png)
![image](https://user-images.githubusercontent.com/5857946/76810197-35464680-6828-11ea-8eab-55f1bc5c6cd8.png)

**Comment by liuyongqing** [comment]
你好，我这边用5.6.17版本测试，头部上传带中文字符，请求是正常通过的哈，如您这边仍然报错，可提工单继续排查，另外，用户自定义key的格式为：x-cos-meta-xxx:value
