### ISSUE TITLE
关于 copyobject 的疑问

### ISSUE THREAD

**Issue by zhric** [tencentyun/cos-java-sdk-v5#61]
拷贝方法执行完未报错，就说明文件已经拷贝过去了吗？
此时我马上去下载新产生的文件，可以保证文件一定正确不？
我copy完以后去调取文件元数据的getContentMD5 发现是空的

**Comment by liuyongqing** [comment]
你好，1. 调用COSClient的copyObject，在拷贝过程中如果有客户端和服务端错误，会抛出异常；2. 服务端会确保从源拷贝到目的的数据一致性；3. getObjectMetadata返回的是etag，服务端不会直接返回content-md5头部哈，注：s3协议分块上传的对象，对应的etag不是md5，只是一个id；如果要做数据校验，可以用cos的crc64校验：https://cloud.tencent.com/document/product/436/40334

**Comment by zhric** [comment]
crc64是什么时候上线的呢？我们公司已经用cos大概4年了，是不是全部都有crc64返回？
