### ISSUE TITLE
请问如何支持MultipartFile类型文件

### ISSUE THREAD

**Issue by xiaozhu5615** [tencentyun/cos-java-sdk-v5#7]
请问如何支持MultipartFile类型文件

**Comment by wucheng** [comment]
分块类型文件可使用TransferManager类，自动进行文件的分块，详见demo
https://github.com/tencentyun/cos-java-sdk-v5/blob/master/src/main/java/com/qcloud/cos/demo/TransferManagerDemo.java

或SDK 文档
https://cloud.tencent.com/document/product/436/12263#.E9.AB.98.E7.BA.A7-api-.E6.96.87.E4.BB.B6.E4.B8.8A.E4.BC.A0(.E6.8E.A8.E8.8D.90)
