### ISSUE TITLE
关于使用“COS 持久化处理”接口遇到的问题

### ISSUE THREAD

**Issue by lazyboywu** [tencentyun/cos-java-sdk-v5#75]
新的文档中[持久化处理](https://cloud.tencent.com/document/product/460/18147)一节中，说：

`您只需要在请求包头部中加入 Pic-Operations 项并设置好相应参数，就可在图片上传时实现相应的图片处理，并可将原图和处理结果存入到 COS。`
`图片上传的请求包与 COS V5 简单上传文件接口一致，只在请求包头部增加图片处理参数。`

也提到了，你处理的后的结果是通过 http Response 的 content 中的 UploadResult 节点返回：
```xml
<UploadResult>
  <OriginalInfo>
  ...
  </OriginalInfo>
  <ProcessResults>
  ...
  </ProcessResults>
</UploadResult>
```

如果直接使用 CosClient 的 putObject 上传文件，经过 CosMetadataResponseHandler 处理，Response 的 content 就丢弃了，也就是说，无法通过 putObject 获取 Pic-Operations 的处理结果，只能自己全部实现整个上传过程。这个问题能修复下么？

**Comment by 563750789** [comment]
当前SDK暂未支持数据万象上传 暂时使用需要自行包装Api，后续迭代会支持该功能。
