### ISSUE TITLE
UserMetadata的value中添加中文时会报Code: 403 SignatureDoesNotMatch

### ISSUE THREAD

**Issue by littlemon95** [tencentyun/cos-java-sdk-v5#86]
version：5.6.38
java: 1.8.0_191

目前的解决方法是在添加metadata时，手动对value值再进行一次urlencode，但是这样在控制台看到的信息是编码后的。
在COSSigner里对headers已经进行了urlencode，不明白为什么还是会报签名失败

**Comment by wenbobuaa** [comment]
有没有可能是本地编译器的编码问题？用你的版本我这里没法复现出来。
