### ISSUE TITLE
V5.2.4-COSSigner类buildAuthorizationStr方法参数设计不合理

### ISSUE THREAD

**Issue by ccfenghe** [tencentyun/cos-java-sdk-v5#9]
COSSigner类本身具有过期时间属性private long signExpiredTime，在调用buildAuthorizationStr方法时，还需使用Date型参数，设计冗余，调用起来麻烦，且通过属性设置的过期时间和方法里的过期时间不知道以哪个为准。V5.1.4版本的buildAuthorizationStr方法的参数设计已经可以满足需求。在升级其他功能时发现方法调用改变得比较难用。

**Comment by liuyongqing** [comment]
非常感谢您提出的建议，signExpiredTime变量已从COSSigner类中移除
